# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\Connectui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogConnect(object):
    def setupUi(self, DialogConnect):
        DialogConnect.setObjectName(_fromUtf8("DialogConnect"))
        DialogConnect.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogConnect.resize(433, 383)
        self.groupBox_Connect = QtGui.QGroupBox(DialogConnect)
        self.groupBox_Connect.setGeometry(QtCore.QRect(10, 10, 411, 201))
        self.groupBox_Connect.setObjectName(_fromUtf8("groupBox_Connect"))
        self.pushButton_NetLink = QtGui.QPushButton(self.groupBox_Connect)
        self.pushButton_NetLink.setGeometry(QtCore.QRect(40, 30, 75, 23))
        self.pushButton_NetLink.setObjectName(_fromUtf8("pushButton_NetLink"))
        self.pushButton_SerialLink = QtGui.QPushButton(self.groupBox_Connect)
        self.pushButton_SerialLink.setGeometry(QtCore.QRect(40, 90, 75, 23))
        self.pushButton_SerialLink.setObjectName(_fromUtf8("pushButton_SerialLink"))
        self.lineEdit_NetName = QtGui.QLineEdit(self.groupBox_Connect)
        self.lineEdit_NetName.setGeometry(QtCore.QRect(240, 20, 161, 20))
        self.lineEdit_NetName.setObjectName(_fromUtf8("lineEdit_NetName"))
        self.lineEdit_NetHostIP = QtGui.QLineEdit(self.groupBox_Connect)
        self.lineEdit_NetHostIP.setGeometry(QtCore.QRect(240, 80, 161, 20))
        self.lineEdit_NetHostIP.setObjectName(_fromUtf8("lineEdit_NetHostIP"))
        self.lineEdit_NetUser = QtGui.QLineEdit(self.groupBox_Connect)
        self.lineEdit_NetUser.setGeometry(QtCore.QRect(240, 140, 161, 20))
        self.lineEdit_NetUser.setObjectName(_fromUtf8("lineEdit_NetUser"))
        self.lineEdit_NetPasswd = QtGui.QLineEdit(self.groupBox_Connect)
        self.lineEdit_NetPasswd.setGeometry(QtCore.QRect(240, 170, 161, 20))
        self.lineEdit_NetPasswd.setObjectName(_fromUtf8("lineEdit_NetPasswd"))
        self.label = QtGui.QLabel(self.groupBox_Connect)
        self.label.setGeometry(QtCore.QRect(160, 19, 54, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox_Connect)
        self.label_2.setGeometry(QtCore.QRect(160, 49, 54, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_Connect)
        self.label_3.setGeometry(QtCore.QRect(160, 78, 54, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_Connect)
        self.label_4.setGeometry(QtCore.QRect(160, 109, 54, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_Connect)
        self.label_5.setGeometry(QtCore.QRect(160, 137, 54, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_Connect)
        self.label_6.setGeometry(QtCore.QRect(160, 166, 54, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.comboBox_NetProtocol = QtGui.QComboBox(self.groupBox_Connect)
        self.comboBox_NetProtocol.setGeometry(QtCore.QRect(240, 50, 161, 22))
        self.comboBox_NetProtocol.setStyleSheet(_fromUtf8(""))
        self.comboBox_NetProtocol.setMaxVisibleItems(2)
        self.comboBox_NetProtocol.setObjectName(_fromUtf8("comboBox_NetProtocol"))
        self.comboBox_NetProtocol.addItem(_fromUtf8(""))
        self.comboBox_NetProtocol.addItem(_fromUtf8(""))
        self.lineEdit_NetPort = QtGui.QLineEdit(self.groupBox_Connect)
        self.lineEdit_NetPort.setGeometry(QtCore.QRect(240, 110, 161, 20))
        self.lineEdit_NetPort.setObjectName(_fromUtf8("lineEdit_NetPort"))
        self.groupBox_Other = QtGui.QGroupBox(DialogConnect)
        self.groupBox_Other.setGeometry(QtCore.QRect(0, 220, 421, 111))
        self.groupBox_Other.setObjectName(_fromUtf8("groupBox_Other"))
        self.label_7 = QtGui.QLabel(self.groupBox_Other)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.groupBox_Other)
        self.label_9.setGeometry(QtCore.QRect(20, 50, 91, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_Other)
        self.label_10.setGeometry(QtCore.QRect(20, 80, 101, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_PlatformIP = QtGui.QLineEdit(self.groupBox_Other)
        self.lineEdit_PlatformIP.setGeometry(QtCore.QRect(120, 50, 201, 20))
        self.lineEdit_PlatformIP.setObjectName(_fromUtf8("lineEdit_PlatformIP"))
        self.lineEdit_ReportPath = QtGui.QLineEdit(self.groupBox_Other)
        self.lineEdit_ReportPath.setGeometry(QtCore.QRect(120, 80, 201, 20))
        self.lineEdit_ReportPath.setObjectName(_fromUtf8("lineEdit_ReportPath"))
        self.pushButton_CheckAddress = QtGui.QPushButton(self.groupBox_Other)
        self.pushButton_CheckAddress.setGeometry(QtCore.QRect(330, 20, 75, 23))
        self.pushButton_CheckAddress.setObjectName(_fromUtf8("pushButton_CheckAddress"))
        self.pushButton_CheckPath = QtGui.QPushButton(self.groupBox_Other)
        self.pushButton_CheckPath.setGeometry(QtCore.QRect(330, 80, 75, 23))
        self.pushButton_CheckPath.setObjectName(_fromUtf8("pushButton_CheckPath"))
        self.comboBox_LocalIP = QtGui.QComboBox(self.groupBox_Other)
        self.comboBox_LocalIP.setGeometry(QtCore.QRect(120, 20, 201, 22))
        self.comboBox_LocalIP.setObjectName(_fromUtf8("comboBox_LocalIP"))
        self.pushButton_Save = QtGui.QPushButton(DialogConnect)
        self.pushButton_Save.setGeometry(QtCore.QRect(110, 350, 75, 23))
        self.pushButton_Save.setObjectName(_fromUtf8("pushButton_Save"))
        self.pushButton_Connect = QtGui.QPushButton(DialogConnect)
        self.pushButton_Connect.setGeometry(QtCore.QRect(260, 350, 75, 23))
        self.pushButton_Connect.setObjectName(_fromUtf8("pushButton_Connect"))

        self.retranslateUi(DialogConnect)
        self.comboBox_NetProtocol.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DialogConnect)
        DialogConnect.setTabOrder(self.pushButton_NetLink, self.pushButton_SerialLink)
        DialogConnect.setTabOrder(self.pushButton_SerialLink, self.lineEdit_NetName)
        DialogConnect.setTabOrder(self.lineEdit_NetName, self.comboBox_NetProtocol)
        DialogConnect.setTabOrder(self.comboBox_NetProtocol, self.lineEdit_NetHostIP)
        DialogConnect.setTabOrder(self.lineEdit_NetHostIP, self.lineEdit_NetPort)
        DialogConnect.setTabOrder(self.lineEdit_NetPort, self.lineEdit_NetUser)
        DialogConnect.setTabOrder(self.lineEdit_NetUser, self.lineEdit_NetPasswd)
        DialogConnect.setTabOrder(self.lineEdit_NetPasswd, self.pushButton_CheckAddress)
        DialogConnect.setTabOrder(self.pushButton_CheckAddress, self.comboBox_LocalIP)
        DialogConnect.setTabOrder(self.comboBox_LocalIP, self.lineEdit_PlatformIP)
        DialogConnect.setTabOrder(self.lineEdit_PlatformIP, self.pushButton_CheckPath)
        DialogConnect.setTabOrder(self.pushButton_CheckPath, self.lineEdit_ReportPath)
        DialogConnect.setTabOrder(self.lineEdit_ReportPath, self.pushButton_Save)
        DialogConnect.setTabOrder(self.pushButton_Save, self.pushButton_Connect)

    def retranslateUi(self, DialogConnect):
        DialogConnect.setWindowTitle(_translate("DialogConnect", "新建会话属性", None))
        self.groupBox_Connect.setTitle(_translate("DialogConnect", "连接", None))
        self.pushButton_NetLink.setText(_translate("DialogConnect", "网络连接", None))
        self.pushButton_SerialLink.setText(_translate("DialogConnect", "串口连接", None))
        self.label.setText(_translate("DialogConnect", "名称：", None))
        self.label_2.setText(_translate("DialogConnect", "协议：", None))
        self.label_3.setText(_translate("DialogConnect", "主机ip：", None))
        self.label_4.setText(_translate("DialogConnect", "端口号：", None))
        self.label_5.setText(_translate("DialogConnect", "用户名：", None))
        self.label_6.setText(_translate("DialogConnect", "密码：", None))
        self.comboBox_NetProtocol.setItemText(0, _translate("DialogConnect", "SSH", None))
        self.comboBox_NetProtocol.setItemText(1, _translate("DialogConnect", "TELNET", None))
        self.groupBox_Other.setTitle(_translate("DialogConnect", "其它", None))
        self.label_7.setText(_translate("DialogConnect", "本机IP地址：", None))
        self.label_9.setText(_translate("DialogConnect", "平台IP地址：", None))
        self.label_10.setText(_translate("DialogConnect", "报告存放路径：", None))
        self.pushButton_CheckAddress.setText(_translate("DialogConnect", "自动检测", None))
        self.pushButton_CheckPath.setText(_translate("DialogConnect", "选择路径", None))
        self.pushButton_Save.setText(_translate("DialogConnect", "保存", None))
        self.pushButton_Connect.setText(_translate("DialogConnect", "连接", None))

