# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\KDATui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(792, 564)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabMain = QtGui.QTabWidget(self.centralwidget)
        self.tabMain.setGeometry(QtCore.QRect(10, -1, 771, 521))
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.tab_Home = QtGui.QWidget()
        self.tab_Home.setObjectName(_fromUtf8("tab_Home"))
        self.groupBox_Mode = QtGui.QGroupBox(self.tab_Home)
        self.groupBox_Mode.setGeometry(QtCore.QRect(30, 140, 251, 61))
        self.groupBox_Mode.setObjectName(_fromUtf8("groupBox_Mode"))
        self.radioButton_OneKey = QtGui.QRadioButton(self.groupBox_Mode)
        self.radioButton_OneKey.setGeometry(QtCore.QRect(21, 26, 89, 16))
        self.radioButton_OneKey.setObjectName(_fromUtf8("radioButton_OneKey"))
        self.radioButton_Custom = QtGui.QRadioButton(self.groupBox_Mode)
        self.radioButton_Custom.setGeometry(QtCore.QRect(140, 26, 101, 16))
        self.radioButton_Custom.setObjectName(_fromUtf8("radioButton_Custom"))
        self.pushButton_StartAll = QtGui.QPushButton(self.tab_Home)
        self.pushButton_StartAll.setGeometry(QtCore.QRect(30, 280, 101, 51))
        self.pushButton_StartAll.setObjectName(_fromUtf8("pushButton_StartAll"))
        self.pushButton_Email = QtGui.QPushButton(self.tab_Home)
        self.pushButton_Email.setGeometry(QtCore.QRect(190, 280, 91, 51))
        self.pushButton_Email.setObjectName(_fromUtf8("pushButton_Email"))
        self.textBrowser_Home = QtGui.QTextBrowser(self.tab_Home)
        self.textBrowser_Home.setGeometry(QtCore.QRect(310, 40, 421, 311))
        self.textBrowser_Home.setObjectName(_fromUtf8("textBrowser_Home"))
        self.progressBar_Home = QtGui.QProgressBar(self.tab_Home)
        self.progressBar_Home.setGeometry(QtCore.QRect(310, 420, 411, 23))
        self.progressBar_Home.setProperty("value", 24)
        self.progressBar_Home.setObjectName(_fromUtf8("progressBar_Home"))
        self.label = QtGui.QLabel(self.tab_Home)
        self.label.setGeometry(QtCore.QRect(310, 390, 72, 15))
        self.label.setObjectName(_fromUtf8("label"))
        self.tabMain.addTab(self.tab_Home, _fromUtf8(""))
        self.tab_System = QtGui.QWidget()
        self.tab_System.setObjectName(_fromUtf8("tab_System"))
        self.groupBox_SysItem = QtGui.QGroupBox(self.tab_System)
        self.groupBox_SysItem.setGeometry(QtCore.QRect(30, 50, 221, 121))
        self.groupBox_SysItem.setObjectName(_fromUtf8("groupBox_SysItem"))
        self.checkBox_SysE2prom = QtGui.QCheckBox(self.groupBox_SysItem)
        self.checkBox_SysE2prom.setGeometry(QtCore.QRect(20, 20, 131, 19))
        self.checkBox_SysE2prom.setObjectName(_fromUtf8("checkBox_SysE2prom"))
        self.checkBox_SysHardware = QtGui.QCheckBox(self.groupBox_SysItem)
        self.checkBox_SysHardware.setGeometry(QtCore.QRect(20, 40, 131, 19))
        self.checkBox_SysHardware.setObjectName(_fromUtf8("checkBox_SysHardware"))
        self.checkBox_SysSoftware = QtGui.QCheckBox(self.groupBox_SysItem)
        self.checkBox_SysSoftware.setGeometry(QtCore.QRect(20, 60, 131, 19))
        self.checkBox_SysSoftware.setObjectName(_fromUtf8("checkBox_SysSoftware"))
        self.checkBox_SysAll = QtGui.QCheckBox(self.groupBox_SysItem)
        self.checkBox_SysAll.setGeometry(QtCore.QRect(20, 90, 131, 19))
        self.checkBox_SysAll.setChecked(False)
        self.checkBox_SysAll.setObjectName(_fromUtf8("checkBox_SysAll"))
        self.textBrowser_Sys = QtGui.QTextBrowser(self.tab_System)
        self.textBrowser_Sys.setGeometry(QtCore.QRect(310, 40, 421, 311))
        self.textBrowser_Sys.setObjectName(_fromUtf8("textBrowser_Sys"))
        self.progressBar_Sys = QtGui.QProgressBar(self.tab_System)
        self.progressBar_Sys.setGeometry(QtCore.QRect(310, 420, 411, 23))
        self.progressBar_Sys.setProperty("value", 24)
        self.progressBar_Sys.setObjectName(_fromUtf8("progressBar_Sys"))
        self.label_2 = QtGui.QLabel(self.tab_System)
        self.label_2.setGeometry(QtCore.QRect(310, 390, 72, 15))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.groupBox_SysSet = QtGui.QGroupBox(self.tab_System)
        self.groupBox_SysSet.setGeometry(QtCore.QRect(30, 400, 221, 61))
        self.groupBox_SysSet.setObjectName(_fromUtf8("groupBox_SysSet"))
        self.pushButton_SysSave = QtGui.QPushButton(self.groupBox_SysSet)
        self.pushButton_SysSave.setGeometry(QtCore.QRect(10, 21, 75, 23))
        self.pushButton_SysSave.setObjectName(_fromUtf8("pushButton_SysSave"))
        self.pushButton_SysStart = QtGui.QPushButton(self.groupBox_SysSet)
        self.pushButton_SysStart.setGeometry(QtCore.QRect(130, 20, 75, 23))
        self.pushButton_SysStart.setObjectName(_fromUtf8("pushButton_SysStart"))
        self.tabMain.addTab(self.tab_System, _fromUtf8(""))
        self.tab_Run = QtGui.QWidget()
        self.tab_Run.setObjectName(_fromUtf8("tab_Run"))
        self.textBrowser_Run = QtGui.QTextBrowser(self.tab_Run)
        self.textBrowser_Run.setGeometry(QtCore.QRect(310, 40, 421, 311))
        self.textBrowser_Run.setObjectName(_fromUtf8("textBrowser_Run"))
        self.label_7 = QtGui.QLabel(self.tab_Run)
        self.label_7.setGeometry(QtCore.QRect(310, 390, 72, 15))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.progressBar_Run = QtGui.QProgressBar(self.tab_Run)
        self.progressBar_Run.setGeometry(QtCore.QRect(310, 420, 411, 23))
        self.progressBar_Run.setProperty("value", 24)
        self.progressBar_Run.setObjectName(_fromUtf8("progressBar_Run"))
        self.groupBox_RunSet = QtGui.QGroupBox(self.tab_Run)
        self.groupBox_RunSet.setGeometry(QtCore.QRect(30, 400, 221, 61))
        self.groupBox_RunSet.setObjectName(_fromUtf8("groupBox_RunSet"))
        self.pushButton_RunSave = QtGui.QPushButton(self.groupBox_RunSet)
        self.pushButton_RunSave.setGeometry(QtCore.QRect(10, 21, 75, 23))
        self.pushButton_RunSave.setObjectName(_fromUtf8("pushButton_RunSave"))
        self.pushButton_RunStart = QtGui.QPushButton(self.groupBox_RunSet)
        self.pushButton_RunStart.setGeometry(QtCore.QRect(130, 20, 75, 23))
        self.pushButton_RunStart.setObjectName(_fromUtf8("pushButton_RunStart"))
        self.groupBox_RunItem = QtGui.QGroupBox(self.tab_Run)
        self.groupBox_RunItem.setGeometry(QtCore.QRect(30, 50, 221, 141))
        self.groupBox_RunItem.setObjectName(_fromUtf8("groupBox_RunItem"))
        self.checkBox_Mem = QtGui.QCheckBox(self.groupBox_RunItem)
        self.checkBox_Mem.setGeometry(QtCore.QRect(20, 20, 131, 19))
        self.checkBox_Mem.setObjectName(_fromUtf8("checkBox_Mem"))
        self.checkBox_Cpu = QtGui.QCheckBox(self.groupBox_RunItem)
        self.checkBox_Cpu.setGeometry(QtCore.QRect(20, 40, 131, 19))
        self.checkBox_Cpu.setObjectName(_fromUtf8("checkBox_Cpu"))
        self.checkBox_Interrupt = QtGui.QCheckBox(self.groupBox_RunItem)
        self.checkBox_Interrupt.setGeometry(QtCore.QRect(20, 60, 131, 19))
        self.checkBox_Interrupt.setObjectName(_fromUtf8("checkBox_Interrupt"))
        self.checkBox_RunAll = QtGui.QCheckBox(self.groupBox_RunItem)
        self.checkBox_RunAll.setGeometry(QtCore.QRect(20, 110, 131, 19))
        self.checkBox_RunAll.setObjectName(_fromUtf8("checkBox_RunAll"))
        self.checkBox_Storage = QtGui.QCheckBox(self.groupBox_RunItem)
        self.checkBox_Storage.setGeometry(QtCore.QRect(20, 80, 131, 19))
        self.checkBox_Storage.setObjectName(_fromUtf8("checkBox_Storage"))
        self.groupBox_RunTime = QtGui.QGroupBox(self.tab_Run)
        self.groupBox_RunTime.setGeometry(QtCore.QRect(30, 210, 221, 141))
        self.groupBox_RunTime.setObjectName(_fromUtf8("groupBox_RunTime"))
        self.lineEdit_RunMem = QtGui.QLineEdit(self.groupBox_RunTime)
        self.lineEdit_RunMem.setGeometry(QtCore.QRect(110, 15, 71, 20))
        self.lineEdit_RunMem.setObjectName(_fromUtf8("lineEdit_RunMem"))
        self.label_8 = QtGui.QLabel(self.groupBox_RunTime)
        self.label_8.setGeometry(QtCore.QRect(30, 20, 81, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.groupBox_RunTime)
        self.label_9.setGeometry(QtCore.QRect(30, 50, 81, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_RunTime)
        self.label_10.setGeometry(QtCore.QRect(30, 80, 81, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_RunTime)
        self.label_11.setGeometry(QtCore.QRect(30, 110, 81, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_RunCpu = QtGui.QLineEdit(self.groupBox_RunTime)
        self.lineEdit_RunCpu.setGeometry(QtCore.QRect(110, 46, 71, 20))
        self.lineEdit_RunCpu.setObjectName(_fromUtf8("lineEdit_RunCpu"))
        self.lineEdit_RunInterrupt = QtGui.QLineEdit(self.groupBox_RunTime)
        self.lineEdit_RunInterrupt.setGeometry(QtCore.QRect(110, 78, 71, 20))
        self.lineEdit_RunInterrupt.setObjectName(_fromUtf8("lineEdit_RunInterrupt"))
        self.lineEdit_RunStorage = QtGui.QLineEdit(self.groupBox_RunTime)
        self.lineEdit_RunStorage.setGeometry(QtCore.QRect(110, 108, 71, 20))
        self.lineEdit_RunStorage.setObjectName(_fromUtf8("lineEdit_RunStorage"))
        self.tabMain.addTab(self.tab_Run, _fromUtf8(""))
        self.tab_Network = QtGui.QWidget()
        self.tab_Network.setObjectName(_fromUtf8("tab_Network"))
        self.textBrowser_Net = QtGui.QTextBrowser(self.tab_Network)
        self.textBrowser_Net.setGeometry(QtCore.QRect(310, 40, 421, 311))
        self.textBrowser_Net.setObjectName(_fromUtf8("textBrowser_Net"))
        self.label_3 = QtGui.QLabel(self.tab_Network)
        self.label_3.setGeometry(QtCore.QRect(310, 390, 72, 15))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.progressBar_Net = QtGui.QProgressBar(self.tab_Network)
        self.progressBar_Net.setGeometry(QtCore.QRect(310, 420, 411, 23))
        self.progressBar_Net.setProperty("value", 24)
        self.progressBar_Net.setObjectName(_fromUtf8("progressBar_Net"))
        self.groupBox_NetSet = QtGui.QGroupBox(self.tab_Network)
        self.groupBox_NetSet.setGeometry(QtCore.QRect(30, 400, 221, 61))
        self.groupBox_NetSet.setObjectName(_fromUtf8("groupBox_NetSet"))
        self.pushButton_NetSave = QtGui.QPushButton(self.groupBox_NetSet)
        self.pushButton_NetSave.setGeometry(QtCore.QRect(10, 21, 75, 23))
        self.pushButton_NetSave.setObjectName(_fromUtf8("pushButton_NetSave"))
        self.pushButton_NetStart = QtGui.QPushButton(self.groupBox_NetSet)
        self.pushButton_NetStart.setGeometry(QtCore.QRect(130, 20, 75, 23))
        self.pushButton_NetStart.setObjectName(_fromUtf8("pushButton_NetStart"))
        self.groupBox_NetItem = QtGui.QGroupBox(self.tab_Network)
        self.groupBox_NetItem.setGeometry(QtCore.QRect(30, 50, 221, 151))
        self.groupBox_NetItem.setObjectName(_fromUtf8("groupBox_NetItem"))
        self.checkBox_EthStatus = QtGui.QCheckBox(self.groupBox_NetItem)
        self.checkBox_EthStatus.setGeometry(QtCore.QRect(20, 20, 131, 19))
        self.checkBox_EthStatus.setObjectName(_fromUtf8("checkBox_EthStatus"))
        self.checkBox_LinkStatus = QtGui.QCheckBox(self.groupBox_NetItem)
        self.checkBox_LinkStatus.setGeometry(QtCore.QRect(20, 40, 131, 19))
        self.checkBox_LinkStatus.setObjectName(_fromUtf8("checkBox_LinkStatus"))
        self.checkBox_RxTx = QtGui.QCheckBox(self.groupBox_NetItem)
        self.checkBox_RxTx.setGeometry(QtCore.QRect(20, 60, 131, 19))
        self.checkBox_RxTx.setObjectName(_fromUtf8("checkBox_RxTx"))
        self.checkBox_NetAll = QtGui.QCheckBox(self.groupBox_NetItem)
        self.checkBox_NetAll.setGeometry(QtCore.QRect(20, 125, 131, 19))
        self.checkBox_NetAll.setObjectName(_fromUtf8("checkBox_NetAll"))
        self.checkBox_NetService = QtGui.QCheckBox(self.groupBox_NetItem)
        self.checkBox_NetService.setGeometry(QtCore.QRect(20, 80, 131, 19))
        self.checkBox_NetService.setObjectName(_fromUtf8("checkBox_NetService"))
        self.checkBox_Capture = QtGui.QCheckBox(self.groupBox_NetItem)
        self.checkBox_Capture.setGeometry(QtCore.QRect(20, 100, 131, 19))
        self.checkBox_Capture.setObjectName(_fromUtf8("checkBox_Capture"))
        self.groupBox_NetTime = QtGui.QGroupBox(self.tab_Network)
        self.groupBox_NetTime.setGeometry(QtCore.QRect(30, 210, 221, 141))
        self.groupBox_NetTime.setObjectName(_fromUtf8("groupBox_NetTime"))
        self.lineEdit_NetLinkStatus = QtGui.QLineEdit(self.groupBox_NetTime)
        self.lineEdit_NetLinkStatus.setGeometry(QtCore.QRect(110, 15, 71, 20))
        self.lineEdit_NetLinkStatus.setObjectName(_fromUtf8("lineEdit_NetLinkStatus"))
        self.label_12 = QtGui.QLabel(self.groupBox_NetTime)
        self.label_12.setGeometry(QtCore.QRect(30, 20, 81, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_NetTime)
        self.label_13.setGeometry(QtCore.QRect(30, 50, 81, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_NetTime)
        self.label_14.setGeometry(QtCore.QRect(30, 80, 81, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_NetTime)
        self.label_15.setGeometry(QtCore.QRect(30, 110, 81, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lineEdit_NetRxTx = QtGui.QLineEdit(self.groupBox_NetTime)
        self.lineEdit_NetRxTx.setGeometry(QtCore.QRect(110, 46, 71, 20))
        self.lineEdit_NetRxTx.setObjectName(_fromUtf8("lineEdit_NetRxTx"))
        self.lineEdit_NetService = QtGui.QLineEdit(self.groupBox_NetTime)
        self.lineEdit_NetService.setGeometry(QtCore.QRect(110, 78, 71, 20))
        self.lineEdit_NetService.setObjectName(_fromUtf8("lineEdit_NetService"))
        self.lineEdit_NetCapture = QtGui.QLineEdit(self.groupBox_NetTime)
        self.lineEdit_NetCapture.setGeometry(QtCore.QRect(110, 108, 71, 20))
        self.lineEdit_NetCapture.setObjectName(_fromUtf8("lineEdit_NetCapture"))
        self.tabMain.addTab(self.tab_Network, _fromUtf8(""))
        self.tab_Media = QtGui.QWidget()
        self.tab_Media.setObjectName(_fromUtf8("tab_Media"))
        self.textBrowser_Media = QtGui.QTextBrowser(self.tab_Media)
        self.textBrowser_Media.setGeometry(QtCore.QRect(310, 40, 421, 311))
        self.textBrowser_Media.setObjectName(_fromUtf8("textBrowser_Media"))
        self.label_4 = QtGui.QLabel(self.tab_Media)
        self.label_4.setGeometry(QtCore.QRect(310, 390, 72, 15))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.progressBar_Media = QtGui.QProgressBar(self.tab_Media)
        self.progressBar_Media.setGeometry(QtCore.QRect(310, 420, 411, 23))
        self.progressBar_Media.setProperty("value", 24)
        self.progressBar_Media.setObjectName(_fromUtf8("progressBar_Media"))
        self.groupBox_MediaSet = QtGui.QGroupBox(self.tab_Media)
        self.groupBox_MediaSet.setGeometry(QtCore.QRect(30, 400, 221, 61))
        self.groupBox_MediaSet.setObjectName(_fromUtf8("groupBox_MediaSet"))
        self.pushButton_MediaSave = QtGui.QPushButton(self.groupBox_MediaSet)
        self.pushButton_MediaSave.setGeometry(QtCore.QRect(10, 21, 75, 23))
        self.pushButton_MediaSave.setObjectName(_fromUtf8("pushButton_MediaSave"))
        self.pushButton_MediaStart = QtGui.QPushButton(self.groupBox_MediaSet)
        self.pushButton_MediaStart.setGeometry(QtCore.QRect(130, 20, 75, 23))
        self.pushButton_MediaStart.setObjectName(_fromUtf8("pushButton_MediaStart"))
        self.groupBox_MediaItem = QtGui.QGroupBox(self.tab_Media)
        self.groupBox_MediaItem.setGeometry(QtCore.QRect(30, 50, 221, 101))
        self.groupBox_MediaItem.setObjectName(_fromUtf8("groupBox_MediaItem"))
        self.checkBox_Encode = QtGui.QCheckBox(self.groupBox_MediaItem)
        self.checkBox_Encode.setGeometry(QtCore.QRect(20, 20, 131, 19))
        self.checkBox_Encode.setObjectName(_fromUtf8("checkBox_Encode"))
        self.checkBox_Decode = QtGui.QCheckBox(self.groupBox_MediaItem)
        self.checkBox_Decode.setGeometry(QtCore.QRect(20, 40, 131, 19))
        self.checkBox_Decode.setObjectName(_fromUtf8("checkBox_Decode"))
        self.checkBox_MediaAll = QtGui.QCheckBox(self.groupBox_MediaItem)
        self.checkBox_MediaAll.setGeometry(QtCore.QRect(20, 70, 131, 19))
        self.checkBox_MediaAll.setObjectName(_fromUtf8("checkBox_MediaAll"))
        self.groupBox_MediaTime = QtGui.QGroupBox(self.tab_Media)
        self.groupBox_MediaTime.setGeometry(QtCore.QRect(30, 210, 221, 81))
        self.groupBox_MediaTime.setObjectName(_fromUtf8("groupBox_MediaTime"))
        self.lineEdit_MediaEncode = QtGui.QLineEdit(self.groupBox_MediaTime)
        self.lineEdit_MediaEncode.setGeometry(QtCore.QRect(110, 15, 71, 20))
        self.lineEdit_MediaEncode.setObjectName(_fromUtf8("lineEdit_MediaEncode"))
        self.label_16 = QtGui.QLabel(self.groupBox_MediaTime)
        self.label_16.setGeometry(QtCore.QRect(30, 20, 81, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBox_MediaTime)
        self.label_17.setGeometry(QtCore.QRect(30, 50, 81, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.lineEdit_MediaDecode = QtGui.QLineEdit(self.groupBox_MediaTime)
        self.lineEdit_MediaDecode.setGeometry(QtCore.QRect(110, 46, 71, 20))
        self.lineEdit_MediaDecode.setObjectName(_fromUtf8("lineEdit_MediaDecode"))
        self.tabMain.addTab(self.tab_Media, _fromUtf8(""))
        self.tab_Advance = QtGui.QWidget()
        self.tab_Advance.setObjectName(_fromUtf8("tab_Advance"))
        self.textBrowser_Advanced = QtGui.QTextBrowser(self.tab_Advance)
        self.textBrowser_Advanced.setGeometry(QtCore.QRect(310, 40, 421, 311))
        self.textBrowser_Advanced.setObjectName(_fromUtf8("textBrowser_Advanced"))
        self.label_5 = QtGui.QLabel(self.tab_Advance)
        self.label_5.setGeometry(QtCore.QRect(310, 390, 72, 15))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.progressBar_Advanced = QtGui.QProgressBar(self.tab_Advance)
        self.progressBar_Advanced.setGeometry(QtCore.QRect(310, 420, 411, 23))
        self.progressBar_Advanced.setProperty("value", 24)
        self.progressBar_Advanced.setObjectName(_fromUtf8("progressBar_Advanced"))
        self.groupBox_AdvancedSet = QtGui.QGroupBox(self.tab_Advance)
        self.groupBox_AdvancedSet.setGeometry(QtCore.QRect(30, 400, 221, 61))
        self.groupBox_AdvancedSet.setObjectName(_fromUtf8("groupBox_AdvancedSet"))
        self.pushButton_AdvancedSave = QtGui.QPushButton(self.groupBox_AdvancedSet)
        self.pushButton_AdvancedSave.setGeometry(QtCore.QRect(10, 21, 75, 23))
        self.pushButton_AdvancedSave.setObjectName(_fromUtf8("pushButton_AdvancedSave"))
        self.pushButton_AdvancedStart = QtGui.QPushButton(self.groupBox_AdvancedSet)
        self.pushButton_AdvancedStart.setGeometry(QtCore.QRect(130, 20, 75, 23))
        self.pushButton_AdvancedStart.setObjectName(_fromUtf8("pushButton_AdvancedStart"))
        self.groupBox_AdvancedItem = QtGui.QGroupBox(self.tab_Advance)
        self.groupBox_AdvancedItem.setGeometry(QtCore.QRect(30, 50, 221, 151))
        self.groupBox_AdvancedItem.setObjectName(_fromUtf8("groupBox_AdvancedItem"))
        self.checkBox_AdvancedSysdbg = QtGui.QCheckBox(self.groupBox_AdvancedItem)
        self.checkBox_AdvancedSysdbg.setGeometry(QtCore.QRect(20, 20, 131, 19))
        self.checkBox_AdvancedSysdbg.setObjectName(_fromUtf8("checkBox_AdvancedSysdbg"))
        self.checkBox_AdvancedCpu = QtGui.QCheckBox(self.groupBox_AdvancedItem)
        self.checkBox_AdvancedCpu.setGeometry(QtCore.QRect(20, 40, 131, 19))
        self.checkBox_AdvancedCpu.setObjectName(_fromUtf8("checkBox_AdvancedCpu"))
        self.checkBox_AdvancedDisk = QtGui.QCheckBox(self.groupBox_AdvancedItem)
        self.checkBox_AdvancedDisk.setGeometry(QtCore.QRect(20, 60, 131, 19))
        self.checkBox_AdvancedDisk.setObjectName(_fromUtf8("checkBox_AdvancedDisk"))
        self.checkBox_AdvancedAll = QtGui.QCheckBox(self.groupBox_AdvancedItem)
        self.checkBox_AdvancedAll.setGeometry(QtCore.QRect(20, 125, 131, 19))
        self.checkBox_AdvancedAll.setObjectName(_fromUtf8("checkBox_AdvancedAll"))
        self.checkBox_AdvancedSys = QtGui.QCheckBox(self.groupBox_AdvancedItem)
        self.checkBox_AdvancedSys.setGeometry(QtCore.QRect(20, 80, 131, 19))
        self.checkBox_AdvancedSys.setObjectName(_fromUtf8("checkBox_AdvancedSys"))
        self.checkBox_AdvancedTask = QtGui.QCheckBox(self.groupBox_AdvancedItem)
        self.checkBox_AdvancedTask.setGeometry(QtCore.QRect(20, 100, 131, 19))
        self.checkBox_AdvancedTask.setObjectName(_fromUtf8("checkBox_AdvancedTask"))
        self.groupBox_AdvancedTime = QtGui.QGroupBox(self.tab_Advance)
        self.groupBox_AdvancedTime.setGeometry(QtCore.QRect(30, 210, 221, 141))
        self.groupBox_AdvancedTime.setObjectName(_fromUtf8("groupBox_AdvancedTime"))
        self.lineEdit_AdvancedSysdbg = QtGui.QLineEdit(self.groupBox_AdvancedTime)
        self.lineEdit_AdvancedSysdbg.setGeometry(QtCore.QRect(130, 15, 71, 20))
        self.lineEdit_AdvancedSysdbg.setObjectName(_fromUtf8("lineEdit_AdvancedSysdbg"))
        self.label_20 = QtGui.QLabel(self.groupBox_AdvancedTime)
        self.label_20.setGeometry(QtCore.QRect(30, 19, 91, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_21 = QtGui.QLabel(self.groupBox_AdvancedTime)
        self.label_21.setGeometry(QtCore.QRect(30, 43, 101, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.groupBox_AdvancedTime)
        self.label_22.setGeometry(QtCore.QRect(30, 69, 101, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.groupBox_AdvancedTime)
        self.label_23.setGeometry(QtCore.QRect(30, 93, 101, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.lineEdit_AdvancedCpu = QtGui.QLineEdit(self.groupBox_AdvancedTime)
        self.lineEdit_AdvancedCpu.setGeometry(QtCore.QRect(130, 40, 71, 20))
        self.lineEdit_AdvancedCpu.setObjectName(_fromUtf8("lineEdit_AdvancedCpu"))
        self.lineEdit_AdvancedDisk = QtGui.QLineEdit(self.groupBox_AdvancedTime)
        self.lineEdit_AdvancedDisk.setGeometry(QtCore.QRect(130, 66, 71, 20))
        self.lineEdit_AdvancedDisk.setObjectName(_fromUtf8("lineEdit_AdvancedDisk"))
        self.lineEdit_AdvancedSys = QtGui.QLineEdit(self.groupBox_AdvancedTime)
        self.lineEdit_AdvancedSys.setGeometry(QtCore.QRect(130, 91, 71, 20))
        self.lineEdit_AdvancedSys.setObjectName(_fromUtf8("lineEdit_AdvancedSys"))
        self.label_27 = QtGui.QLabel(self.groupBox_AdvancedTime)
        self.label_27.setGeometry(QtCore.QRect(30, 117, 101, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.lineEdit_AdvancedTask = QtGui.QLineEdit(self.groupBox_AdvancedTime)
        self.lineEdit_AdvancedTask.setGeometry(QtCore.QRect(130, 116, 71, 20))
        self.lineEdit_AdvancedTask.setObjectName(_fromUtf8("lineEdit_AdvancedTask"))
        self.tabMain.addTab(self.tab_Advance, _fromUtf8(""))
        self.tab_App = QtGui.QWidget()
        self.tab_App.setObjectName(_fromUtf8("tab_App"))
        self.textBrowser_App = QtGui.QTextBrowser(self.tab_App)
        self.textBrowser_App.setGeometry(QtCore.QRect(310, 40, 421, 311))
        self.textBrowser_App.setObjectName(_fromUtf8("textBrowser_App"))
        self.label_6 = QtGui.QLabel(self.tab_App)
        self.label_6.setGeometry(QtCore.QRect(310, 390, 72, 15))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.progressBar_App = QtGui.QProgressBar(self.tab_App)
        self.progressBar_App.setGeometry(QtCore.QRect(310, 420, 411, 23))
        self.progressBar_App.setProperty("value", 24)
        self.progressBar_App.setObjectName(_fromUtf8("progressBar_App"))
        self.groupBox_AppSet = QtGui.QGroupBox(self.tab_App)
        self.groupBox_AppSet.setGeometry(QtCore.QRect(30, 400, 221, 61))
        self.groupBox_AppSet.setObjectName(_fromUtf8("groupBox_AppSet"))
        self.pushButton_AppSave = QtGui.QPushButton(self.groupBox_AppSet)
        self.pushButton_AppSave.setGeometry(QtCore.QRect(10, 21, 75, 23))
        self.pushButton_AppSave.setObjectName(_fromUtf8("pushButton_AppSave"))
        self.pushButton_AppStart = QtGui.QPushButton(self.groupBox_AppSet)
        self.pushButton_AppStart.setGeometry(QtCore.QRect(130, 20, 75, 23))
        self.pushButton_AppStart.setObjectName(_fromUtf8("pushButton_AppStart"))
        self.groupBox_AppItem = QtGui.QGroupBox(self.tab_App)
        self.groupBox_AppItem.setGeometry(QtCore.QRect(30, 50, 221, 91))
        self.groupBox_AppItem.setObjectName(_fromUtf8("groupBox_AppItem"))
        self.checkBox_AppSourceStatus = QtGui.QCheckBox(self.groupBox_AppItem)
        self.checkBox_AppSourceStatus.setGeometry(QtCore.QRect(20, 20, 181, 19))
        self.checkBox_AppSourceStatus.setObjectName(_fromUtf8("checkBox_AppSourceStatus"))
        self.checkBox_AppStability = QtGui.QCheckBox(self.groupBox_AppItem)
        self.checkBox_AppStability.setGeometry(QtCore.QRect(20, 40, 131, 19))
        self.checkBox_AppStability.setObjectName(_fromUtf8("checkBox_AppStability"))
        self.checkBox_AppAll = QtGui.QCheckBox(self.groupBox_AppItem)
        self.checkBox_AppAll.setGeometry(QtCore.QRect(20, 66, 131, 19))
        self.checkBox_AppAll.setObjectName(_fromUtf8("checkBox_AppAll"))
        self.groupBox_AppTime = QtGui.QGroupBox(self.tab_App)
        self.groupBox_AppTime.setGeometry(QtCore.QRect(30, 210, 221, 81))
        self.groupBox_AppTime.setObjectName(_fromUtf8("groupBox_AppTime"))
        self.lineEdit_AppSourceStatus = QtGui.QLineEdit(self.groupBox_AppTime)
        self.lineEdit_AppSourceStatus.setGeometry(QtCore.QRect(120, 15, 71, 20))
        self.lineEdit_AppSourceStatus.setObjectName(_fromUtf8("lineEdit_AppSourceStatus"))
        self.label_24 = QtGui.QLabel(self.groupBox_AppTime)
        self.label_24.setGeometry(QtCore.QRect(30, 20, 81, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.groupBox_AppTime)
        self.label_25.setGeometry(QtCore.QRect(30, 50, 81, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.lineEdit_AppStability = QtGui.QLineEdit(self.groupBox_AppTime)
        self.lineEdit_AppStability.setGeometry(QtCore.QRect(120, 46, 71, 20))
        self.lineEdit_AppStability.setObjectName(_fromUtf8("lineEdit_AppStability"))
        self.tabMain.addTab(self.tab_App, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuLink = QtGui.QMenu(self.menubar)
        self.menuLink.setObjectName(_fromUtf8("menuLink"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_New = QtGui.QAction(MainWindow)
        self.action_New.setObjectName(_fromUtf8("action_New"))
        self.action_Open = QtGui.QAction(MainWindow)
        self.action_Open.setObjectName(_fromUtf8("action_Open"))
        self.action_Break = QtGui.QAction(MainWindow)
        self.action_Break.setObjectName(_fromUtf8("action_Break"))
        self.action_Exit = QtGui.QAction(MainWindow)
        self.action_Exit.setObjectName(_fromUtf8("action_Exit"))
        self.action_Document = QtGui.QAction(MainWindow)
        self.action_Document.setObjectName(_fromUtf8("action_Document"))
        self.action_About = QtGui.QAction(MainWindow)
        self.action_About.setObjectName(_fromUtf8("action_About"))
        self.menuLink.addAction(self.action_New)
        self.menuLink.addAction(self.action_Open)
        self.menuLink.addAction(self.action_Break)
        self.menuLink.addAction(self.action_Exit)
        self.menuHelp.addAction(self.action_Document)
        self.menuHelp.addAction(self.action_About)
        self.menubar.addAction(self.menuLink.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabMain, self.radioButton_OneKey)
        MainWindow.setTabOrder(self.radioButton_OneKey, self.radioButton_Custom)
        MainWindow.setTabOrder(self.radioButton_Custom, self.pushButton_StartAll)
        MainWindow.setTabOrder(self.pushButton_StartAll, self.pushButton_Email)
        MainWindow.setTabOrder(self.pushButton_Email, self.textBrowser_Home)
        MainWindow.setTabOrder(self.textBrowser_Home, self.checkBox_SysE2prom)
        MainWindow.setTabOrder(self.checkBox_SysE2prom, self.checkBox_SysHardware)
        MainWindow.setTabOrder(self.checkBox_SysHardware, self.checkBox_SysSoftware)
        MainWindow.setTabOrder(self.checkBox_SysSoftware, self.checkBox_SysAll)
        MainWindow.setTabOrder(self.checkBox_SysAll, self.pushButton_SysSave)
        MainWindow.setTabOrder(self.pushButton_SysSave, self.pushButton_SysStart)
        MainWindow.setTabOrder(self.pushButton_SysStart, self.textBrowser_Sys)
        MainWindow.setTabOrder(self.textBrowser_Sys, self.checkBox_Mem)
        MainWindow.setTabOrder(self.checkBox_Mem, self.checkBox_Cpu)
        MainWindow.setTabOrder(self.checkBox_Cpu, self.checkBox_Interrupt)
        MainWindow.setTabOrder(self.checkBox_Interrupt, self.checkBox_Storage)
        MainWindow.setTabOrder(self.checkBox_Storage, self.checkBox_RunAll)
        MainWindow.setTabOrder(self.checkBox_RunAll, self.lineEdit_RunMem)
        MainWindow.setTabOrder(self.lineEdit_RunMem, self.lineEdit_RunCpu)
        MainWindow.setTabOrder(self.lineEdit_RunCpu, self.lineEdit_RunInterrupt)
        MainWindow.setTabOrder(self.lineEdit_RunInterrupt, self.lineEdit_RunStorage)
        MainWindow.setTabOrder(self.lineEdit_RunStorage, self.pushButton_RunSave)
        MainWindow.setTabOrder(self.pushButton_RunSave, self.pushButton_RunStart)
        MainWindow.setTabOrder(self.pushButton_RunStart, self.textBrowser_Run)
        MainWindow.setTabOrder(self.textBrowser_Run, self.checkBox_EthStatus)
        MainWindow.setTabOrder(self.checkBox_EthStatus, self.checkBox_LinkStatus)
        MainWindow.setTabOrder(self.checkBox_LinkStatus, self.checkBox_RxTx)
        MainWindow.setTabOrder(self.checkBox_RxTx, self.checkBox_NetService)
        MainWindow.setTabOrder(self.checkBox_NetService, self.checkBox_Capture)
        MainWindow.setTabOrder(self.checkBox_Capture, self.checkBox_NetAll)
        MainWindow.setTabOrder(self.checkBox_NetAll, self.lineEdit_NetLinkStatus)
        MainWindow.setTabOrder(self.lineEdit_NetLinkStatus, self.lineEdit_NetRxTx)
        MainWindow.setTabOrder(self.lineEdit_NetRxTx, self.lineEdit_NetService)
        MainWindow.setTabOrder(self.lineEdit_NetService, self.lineEdit_NetCapture)
        MainWindow.setTabOrder(self.lineEdit_NetCapture, self.pushButton_NetSave)
        MainWindow.setTabOrder(self.pushButton_NetSave, self.pushButton_NetStart)
        MainWindow.setTabOrder(self.pushButton_NetStart, self.textBrowser_Net)
        MainWindow.setTabOrder(self.textBrowser_Net, self.checkBox_Encode)
        MainWindow.setTabOrder(self.checkBox_Encode, self.checkBox_Decode)
        MainWindow.setTabOrder(self.checkBox_Decode, self.checkBox_MediaAll)
        MainWindow.setTabOrder(self.checkBox_MediaAll, self.lineEdit_MediaEncode)
        MainWindow.setTabOrder(self.lineEdit_MediaEncode, self.lineEdit_MediaDecode)
        MainWindow.setTabOrder(self.lineEdit_MediaDecode, self.pushButton_MediaSave)
        MainWindow.setTabOrder(self.pushButton_MediaSave, self.pushButton_MediaStart)
        MainWindow.setTabOrder(self.pushButton_MediaStart, self.textBrowser_Media)
        MainWindow.setTabOrder(self.textBrowser_Media, self.checkBox_AdvancedSysdbg)
        MainWindow.setTabOrder(self.checkBox_AdvancedSysdbg, self.checkBox_AdvancedCpu)
        MainWindow.setTabOrder(self.checkBox_AdvancedCpu, self.checkBox_AdvancedDisk)
        MainWindow.setTabOrder(self.checkBox_AdvancedDisk, self.checkBox_AdvancedSys)
        MainWindow.setTabOrder(self.checkBox_AdvancedSys, self.checkBox_AdvancedTask)
        MainWindow.setTabOrder(self.checkBox_AdvancedTask, self.checkBox_AdvancedAll)
        MainWindow.setTabOrder(self.checkBox_AdvancedAll, self.lineEdit_AdvancedSysdbg)
        MainWindow.setTabOrder(self.lineEdit_AdvancedSysdbg, self.lineEdit_AdvancedCpu)
        MainWindow.setTabOrder(self.lineEdit_AdvancedCpu, self.lineEdit_AdvancedDisk)
        MainWindow.setTabOrder(self.lineEdit_AdvancedDisk, self.lineEdit_AdvancedSys)
        MainWindow.setTabOrder(self.lineEdit_AdvancedSys, self.lineEdit_AdvancedTask)
        MainWindow.setTabOrder(self.lineEdit_AdvancedTask, self.pushButton_AdvancedSave)
        MainWindow.setTabOrder(self.pushButton_AdvancedSave, self.pushButton_AdvancedStart)
        MainWindow.setTabOrder(self.pushButton_AdvancedStart, self.textBrowser_Advanced)
        MainWindow.setTabOrder(self.textBrowser_Advanced, self.checkBox_AppSourceStatus)
        MainWindow.setTabOrder(self.checkBox_AppSourceStatus, self.checkBox_AppStability)
        MainWindow.setTabOrder(self.checkBox_AppStability, self.checkBox_AppAll)
        MainWindow.setTabOrder(self.checkBox_AppAll, self.lineEdit_AppSourceStatus)
        MainWindow.setTabOrder(self.lineEdit_AppSourceStatus, self.lineEdit_AppStability)
        MainWindow.setTabOrder(self.lineEdit_AppStability, self.pushButton_AppSave)
        MainWindow.setTabOrder(self.pushButton_AppSave, self.pushButton_AppStart)
        MainWindow.setTabOrder(self.pushButton_AppStart, self.textBrowser_App)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "KDAT", None))
        self.groupBox_Mode.setTitle(_translate("MainWindow", "模式选择", None))
        self.radioButton_OneKey.setText(_translate("MainWindow", "一键分析", None))
        self.radioButton_Custom.setText(_translate("MainWindow", "自定义分析", None))
        self.pushButton_StartAll.setText(_translate("MainWindow", "Start", None))
        self.pushButton_Email.setText(_translate("MainWindow", "发送报告", None))
        self.textBrowser_Home.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.label.setText(_translate("MainWindow", "进度显示：", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab_Home), _translate("MainWindow", "主页", None))
        self.groupBox_SysItem.setTitle(_translate("MainWindow", "选择分析项（可多选）", None))
        self.checkBox_SysE2prom.setText(_translate("MainWindow", "EEPROM分析", None))
        self.checkBox_SysHardware.setText(_translate("MainWindow", "硬件分析", None))
        self.checkBox_SysSoftware.setText(_translate("MainWindow", "软件分析", None))
        self.checkBox_SysAll.setText(_translate("MainWindow", "全选", None))
        self.label_2.setText(_translate("MainWindow", "进度显示：", None))
        self.groupBox_SysSet.setTitle(_translate("MainWindow", "当前页", None))
        self.pushButton_SysSave.setText(_translate("MainWindow", "保存参数", None))
        self.pushButton_SysStart.setText(_translate("MainWindow", "开始分析", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab_System), _translate("MainWindow", "系统分析", None))
        self.label_7.setText(_translate("MainWindow", "进度显示：", None))
        self.groupBox_RunSet.setTitle(_translate("MainWindow", "当前页", None))
        self.pushButton_RunSave.setText(_translate("MainWindow", "保存参数", None))
        self.pushButton_RunStart.setText(_translate("MainWindow", "开始分析", None))
        self.groupBox_RunItem.setTitle(_translate("MainWindow", "选择分析项（可多选）", None))
        self.checkBox_Mem.setText(_translate("MainWindow", "内存状态分析", None))
        self.checkBox_Cpu.setText(_translate("MainWindow", "CPU状态分析", None))
        self.checkBox_Interrupt.setText(_translate("MainWindow", "中断状态分析", None))
        self.checkBox_RunAll.setText(_translate("MainWindow", "全选", None))
        self.checkBox_Storage.setText(_translate("MainWindow", "存储状态分析", None))
        self.groupBox_RunTime.setTitle(_translate("MainWindow", "时间设置（秒）", None))
        self.label_8.setText(_translate("MainWindow", "内存状态：", None))
        self.label_9.setText(_translate("MainWindow", "CPU状态：", None))
        self.label_10.setText(_translate("MainWindow", "中断状态：", None))
        self.label_11.setText(_translate("MainWindow", "存储状态：", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab_Run), _translate("MainWindow", "运行状态", None))
        self.label_3.setText(_translate("MainWindow", "进度显示：", None))
        self.groupBox_NetSet.setTitle(_translate("MainWindow", "当前页", None))
        self.pushButton_NetSave.setText(_translate("MainWindow", "保存参数", None))
        self.pushButton_NetStart.setText(_translate("MainWindow", "开始分析", None))
        self.groupBox_NetItem.setTitle(_translate("MainWindow", "选择分析项（可多选）", None))
        self.checkBox_EthStatus.setText(_translate("MainWindow", "接口状态分析", None))
        self.checkBox_LinkStatus.setText(_translate("MainWindow", "网络连接分析", None))
        self.checkBox_RxTx.setText(_translate("MainWindow", "收发统计分析", None))
        self.checkBox_NetAll.setText(_translate("MainWindow", "全选", None))
        self.checkBox_NetService.setText(_translate("MainWindow", "网络服务分析", None))
        self.checkBox_Capture.setText(_translate("MainWindow", "抓包分析", None))
        self.groupBox_NetTime.setTitle(_translate("MainWindow", "时间设置（秒）", None))
        self.label_12.setText(_translate("MainWindow", "网络连接：", None))
        self.label_13.setText(_translate("MainWindow", "收发统计：", None))
        self.label_14.setText(_translate("MainWindow", "网络服务：", None))
        self.label_15.setText(_translate("MainWindow", "抓包分析：", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab_Network), _translate("MainWindow", "网络分析", None))
        self.label_4.setText(_translate("MainWindow", "进度显示：", None))
        self.groupBox_MediaSet.setTitle(_translate("MainWindow", "当前页", None))
        self.pushButton_MediaSave.setText(_translate("MainWindow", "保存参数", None))
        self.pushButton_MediaStart.setText(_translate("MainWindow", "开始分析", None))
        self.groupBox_MediaItem.setTitle(_translate("MainWindow", "选择分析项（可多选）", None))
        self.checkBox_Encode.setText(_translate("MainWindow", "编码参数分析", None))
        self.checkBox_Decode.setText(_translate("MainWindow", "解码参数分析", None))
        self.checkBox_MediaAll.setText(_translate("MainWindow", "全选", None))
        self.groupBox_MediaTime.setTitle(_translate("MainWindow", "时间设置（秒）", None))
        self.label_16.setText(_translate("MainWindow", "编码参数：", None))
        self.label_17.setText(_translate("MainWindow", "解码参数：", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab_Media), _translate("MainWindow", "媒体分析", None))
        self.label_5.setText(_translate("MainWindow", "进度显示：", None))
        self.groupBox_AdvancedSet.setTitle(_translate("MainWindow", "当前页", None))
        self.pushButton_AdvancedSave.setText(_translate("MainWindow", "保存参数", None))
        self.pushButton_AdvancedStart.setText(_translate("MainWindow", "开始分析", None))
        self.groupBox_AdvancedItem.setTitle(_translate("MainWindow", "选择分析项（可多选）", None))
        self.checkBox_AdvancedSysdbg.setText(_translate("MainWindow", "Sysdbg分析", None))
        self.checkBox_AdvancedCpu.setText(_translate("MainWindow", "CPU性能分析", None))
        self.checkBox_AdvancedDisk.setText(_translate("MainWindow", "磁盘性能分析", None))
        self.checkBox_AdvancedAll.setText(_translate("MainWindow", "全选", None))
        self.checkBox_AdvancedSys.setText(_translate("MainWindow", "系统性能分析", None))
        self.checkBox_AdvancedTask.setText(_translate("MainWindow", "进程线程分析", None))
        self.groupBox_AdvancedTime.setTitle(_translate("MainWindow", "时间设置（秒）", None))
        self.label_20.setText(_translate("MainWindow", "Sysdbg分析：", None))
        self.label_21.setText(_translate("MainWindow", "CPU性能分析：", None))
        self.label_22.setText(_translate("MainWindow", "磁盘性能分析：", None))
        self.label_23.setText(_translate("MainWindow", "系统性能分析：", None))
        self.label_27.setText(_translate("MainWindow", "进程线程分析：", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab_Advance), _translate("MainWindow", "高级分析", None))
        self.label_6.setText(_translate("MainWindow", "进度显示：", None))
        self.groupBox_AppSet.setTitle(_translate("MainWindow", "当前页", None))
        self.pushButton_AppSave.setText(_translate("MainWindow", "保存参数", None))
        self.pushButton_AppStart.setText(_translate("MainWindow", "开始分析", None))
        self.groupBox_AppItem.setTitle(_translate("MainWindow", "选择分析项（可多选）", None))
        self.checkBox_AppSourceStatus.setText(_translate("MainWindow", "业务进程资源占用分析", None))
        self.checkBox_AppStability.setText(_translate("MainWindow", "业务稳定性分析", None))
        self.checkBox_AppAll.setText(_translate("MainWindow", "全选", None))
        self.groupBox_AppTime.setTitle(_translate("MainWindow", "时间设置（秒）", None))
        self.label_24.setText(_translate("MainWindow", "资源占用：", None))
        self.label_25.setText(_translate("MainWindow", "稳定性分析：", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tab_App), _translate("MainWindow", "业务分析", None))
        self.menuLink.setTitle(_translate("MainWindow", "连接", None))
        self.menuHelp.setTitle(_translate("MainWindow", "帮助", None))
        self.action_New.setText(_translate("MainWindow", "新建", None))
        self.action_Open.setText(_translate("MainWindow", "打开", None))
        self.action_Break.setText(_translate("MainWindow", "断开", None))
        self.action_Exit.setText(_translate("MainWindow", "退出", None))
        self.action_Document.setText(_translate("MainWindow", "查看帮助", None))
        self.action_About.setText(_translate("MainWindow", "关于KDAT", None))

